"""empty message

Revision ID: 279928ae8d18
Revises: 
Create Date: 2023-01-27 22:56:28.783280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '279928ae8d18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellido', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('rol_profesor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellido', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('nivel', postgresql.ENUM('basico', 'intermedio', 'avanzado', name='nivel_enum'), nullable=True),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_profesor'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apellido'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_ejercicio', sa.String(length=120), nullable=False),
    sa.Column('series', sa.String(length=80), nullable=False),
    sa.Column('repeticiones', sa.String(length=20), nullable=False),
    sa.Column('peso', sa.String(length=20), nullable=False),
    sa.Column('descanso', sa.String(length=20), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_de_ejercicio')
    )
    op.create_table('ficha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('estatura', sa.Integer(), nullable=False),
    sa.Column('porcentaje_grasa', sa.Integer(), nullable=False),
    sa.Column('porcentaje_musculo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estatura'),
    sa.UniqueConstraint('peso'),
    sa.UniqueConstraint('porcentaje_grasa'),
    sa.UniqueConstraint('porcentaje_musculo')
    )
    op.create_table('reto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('ejercicio', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ejercicio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reto')
    op.drop_table('ficha')
    op.drop_table('ejercicio')
    op.drop_table('estudiante')
    op.drop_table('profesor')
    # ### end Alembic commands ###
