"""empty message

Revision ID: 772e2f80aa23
Revises: 
Create Date: 2023-01-31 03:23:15.674597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772e2f80aa23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_ejercicio', sa.String(length=120), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel'),
    sa.UniqueConstraint('tipo_de_ejercicio')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellido', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('ficha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('porcentaje_grasa', sa.Integer(), nullable=False),
    sa.Column('porcentaje_musculo', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel'),
    sa.UniqueConstraint('peso'),
    sa.UniqueConstraint('porcentaje_grasa'),
    sa.UniqueConstraint('porcentaje_musculo')
    )
    op.create_table('reto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_ejercicio', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_ejercicio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reto')
    op.drop_table('ficha')
    op.drop_table('user')
    op.drop_table('ejercicio')
    # ### end Alembic commands ###
